---
- name: Check status and version of specific Windows services (Read-Only)
  hosts: windows_servers
  gather_facts: yes
  vars:
    monitored_services:
      - name: "Spooler"
        display_name: "Print Spooler"
        product_name: "Windows Driver Foundation"
      - name: "Themes"
        display_name: "Themes"
        product_name: "Themes"
      - name: "BITS"
        display_name: "Background Intelligent Transfer Service"
        product_name: "Background Intelligent Transfer Service"
      - name: "W32Time"
        display_name: "Windows Time"
        product_name: "Windows Time"
      - name: "SplunkUniversalForwarder"
        display_name: "Splunk Universal Forwarder"
        product_name: "UniversalForwarder"
      - name: "Agent"
        display_name: "Security Agent"
        product_name: "Security Agent"

    csv_output_path: "/home/csv/check_service_status_only_{{ ansible_date_time.date }}.csv"
    service_results: []

  tasks:
    - name: Get all services information
      ansible.windows.win_service_info:
      register: all_services

    - name: Gather installed package facts
      ansible.windows.win_package_facts:
      register: package_facts

    - name: Initialize service results list
      set_fact:
        service_results: []

    - name: Check status and version of each monitored service
      set_fact:
        service_results: "{{ service_results + [current_service_status] }}"
      vars:
        service_exists: "{{ all_services.services | selectattr('name', '==', item.name) | list | length > 0 }}"
        found_service: "{{ all_services.services | selectattr('name', '==', item.name) | first }}"
        version_match: "{{ package_facts.packages | selectattr('name', 'search', item.product_name) | list | first }}"
        current_service_status: "{{
          {
            'name': item.name,
            'display_name': item.display_name,
            'status': (found_service.state if service_exists else 'Missing'),
            'start_mode': (found_service.start_mode if service_exists else 'NA'),
            'version': (version_match.version if version_match is defined else 'Unknown'),
            'timestamp': ansible_date_time.iso8601,
            'unique_key': ansible_hostname + '|' + item.name
          }
        }}"
      loop: "{{ monitored_services }}"

    - name: Remove existing CSV file and create new one with header
      delegate_to: localhost
      run_once: true
      copy:
        content: "Hostname,ServiceName,DisplayName,Status,StartMode,Version,Timestamp,UniqueKey\n"
        dest: "{{ csv_output_path }}"
      become: false

    - name: Write service status to CSV on control machine
      delegate_to: localhost
      lineinfile:
        path: "{{ csv_output_path }}"
        line: "{{ ansible_hostname }},{{ item.name }},{{ item.display_name }},{{ item.status }},{{ item.start_mode }},{{ item.version }},{{ item.timestamp }},{{ item.unique_key }}"
        state: present
      loop: "{{ service_results }}"
      become: false
