---
- name: Generate Services CSV with Unique Key
  hosts: windows_servers
  gather_facts: yes
  vars:
    csv_file: "/home/csv/check_services_{{ ansible_date_time.epoch }}.csv"
  tasks:
    - name: Get Windows services information
      ansible.windows.win_service_info:
        name: "{{ item }}"
      loop:
        - Spooler
        - Themes
        - BITS
        - W32Time
        - SplunkUniversalForwarder
      register: service_info
      failed_when: false  # Don't fail if service doesn't exist
      
    - name: Prepare service data with unique key
      set_fact:
        services_data: "{{ services_data | default([]) + [service_item] }}"
      vars:
        service_name: "{{ item.item }}"  # Original service name from the loop
        service_details: "{{ item.services[item.item] | default({}) }}"  # Service details if found
        service_item:
          hostname: "{{ ansible_hostname }}"
          service_name: "{{ service_name }}"
          display_name: "{{ service_details.display_name | default(service_name) }}"
          status: "{{ service_details.state | default('Missing') }}"
          start_mode: "{{ service_details.start_mode | default('NA') }}"
          timestamp: "{{ ansible_date_time.iso8601 }}"
          unique_key: "{{ ansible_hostname }}|{{ service_name }}"
      loop: "{{ service_info.results }}"
      
    - name: Create CSV header
      lineinfile:
        path: "{{ csv_file }}"
        line: "Hostname,ServiceName,DisplayName,Status,StartMode,Timestamp,unique_key"
        create: yes
        state: present
      delegate_to: localhost
      run_once: true
      
    - name: Write service data to CSV
      lineinfile:
        path: "{{ csv_file }}"
        line: "{{ item.hostname }},{{ item.service_name }},\"{{ item.display_name }}\",{{ item.status }},{{ item.start_mode }},{{ item.timestamp }},{{ item.unique_key }}"
        state: present
      loop: "{{ services_data }}"
      delegate_to: localhost

    - name: Upload CSV to Directus via API
      uri:
        url: "{{ directus_url }}/files"
        method: POST
        headers:
          Authorization: "Bearer {{ directus_token }}"
        body_format: form-multipart
        body:
          title: "Services Report {{ ansible_date_time.date }}"
          folder: "{{ directus_folder_id | default(omit) }}"
          file: "{{ lookup('file', csv_file) | b64encode }}"
          filename: "check_services_{{ ansible_date_time.epoch }}.csv"
      delegate_to: localhost
      run_once: true
      register: upload_result
      
    - name: Display upload result
      debug:
        msg: "File uploaded successfully with ID: {{ upload_result.json.data.id | default('Unknown') }}"
      when: upload_result is succeeded
