---
- name: Installing Apache MSI
  hosts: windows_servers

  tasks:
    - name: Download the Apache installer
      ansible.windows.win_get_url:
        url: https://archive.apache.org/dist/httpd/binaries/win32/httpd-2.2.25-win32-x86-no_ssl.msi
        dest: C:\ansible_examples\httpd-2.2.25-win32-x86-no_ssl.msi

    - name: Install MSI
      ansible.windows.win_package:
        path: C:\ansible_examples\httpd-2.2.25-win32-x86-no_ssl.msi
        arguments:
          - /install
          - /passive
          - /norestart
          - /quiet
