# need microsoft.ad collection
- name: Create user
  hosts: windows_servers
  become: no
  gather_facts: no
  tasks:
    - name: Ensure defined user is created 
      microsoft.ad.user:
        name: '{{ username }}'
        identity: '{{ username }}'
        firstname: '{{ firstname }}'
        surname: '{{ lastname }}'
        display_name: '{{ displayname }}'
        password: 4rfv%TGB
        state: present
        email: '{{ username }}@local.domain'
        upn: '{{ username }}@local.domain'
        path: OU=Admins,DC=local,DC=domain
        groups:
          set:
            - Special Admins
            - Domain Users
        attributes:
          set:
            telephoneNumber:
