- name: Create users
  hosts: windows_servers
  become: no
  gather_facts: no

  tasks:
    - name: Ensure user bob is created and use custom credentials to create the user
      microsoft.ad.user:
        name: yx2 y
        identity: yx2
        firstname: yx2
        surname: y
        password: 4rfv%TGB
        state: present
        domain_username: LOCAL\yx2
        domain_password: SomePas2w0rd
        domain_server: AIOSERVER@local.domain
        groups:
          set:
            - Domain Admins
        attributes:
          set:
            telephoneNumber: 1234
