- name: Create users
  hosts: windows_servers
  become: no
  gather_facts: no

  tasks:
    - name: Ensure user bob is created and use custom credentials to create the user
      microsoft.ad.user:
        name: yx2
        identity: yx2
        firstname: yx2
        surname: y
        display_name
        password: 4rfv%TGB
        state: present
        upn: yx2@local.domain
        groups:
          set:
            - Domain Admins
        attributes:
          set:
            telephoneNumber: 1234
