- name: Reboot Windows Machine if updates installed
  hosts: windows_servers
  become: no
  gather_facts: no

  tasks:
    - name: Check for pending updates
      ansible.windows.win_updates:
        state: installed
        
    - name: Check if reboot is pending (for Windows 2012 and newer)
      ansible.windows.win_shell: |
        $Pending = 0
        if (Test-Path "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Component Based Servicing\RebootPending") { $Pending = 1 }
        if (Test-Path "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\WindowsUpdate\Auto Update\RebootRequired") { $Pending = 1 }
        if (Test-Path "HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\PendingFileRenameOperations") { $Pending = 1 }
        if (Test-Path "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\RunOnce") { $Pending = 1 }
        if ($Pending -eq 1) { Write-Host "Reboot is required"; exit 1 }
        else { Write-Host "No reboot required"; exit 0 }
      register: reboot_check
      ignore_errors: yes
      
    - name: Reboot if updates installed
      ansible.windows.win_reboot:
        reboot_timeout: 600
      when: reboot_check.failed
