- name: Update Windows and Reboot if necessary
  hosts: windows_servers
  become: no
  gather_facts: no

  tasks:
    - name: Search for Windows Updates
      ansible.windows.win_updates:
        category_names: '*'
        server_selection: 'windows_update'
        state: searched
      register: check_win_updates_patch_result
      
    - name: Install Windows Updates
      ansible.windows.win_updates:
        category_names: '*'
        server_selection: 'windows_update'
        state: installed
      register: check_win_updates_patch_result  
        
    - name: Check if reboot is pending
      ansible.windows.win_shell: |
        $Pending = 0
        if (Test-Path "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Component Based Servicing\RebootPending") { $Pending = 1 }
        if (Test-Path "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\WindowsUpdate\Auto Update\RebootRequired") { $Pending = 1 }
        if (Test-Path "HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\PendingFileRenameOperations") { $Pending = 1 }
        if (Test-Path "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\RunOnce") { $Pending = 1 }
        if ($Pending -eq 1) { Write-Host "Reboot is required"; exit 1 }
        else { Write-Host "No reboot required"; exit 0 }
      register: reboot_check
      ignore_errors: yes
      
    - name: Reboot if updates installed
      ansible.windows.win_reboot:
        reboot_timeout: 600
      when: reboot_check.failed
