---
- name: List all enabled windows services and highlight stopped automatic service on Windows
  hosts: windows_servers
  gather_facts: no
  tasks:
    - name: List all services on the Windows machine
      ansible.windows.win_service_info:
      register: services_list

    - name: Display the names of enabled services only
      debug:
        msg: "{{ item.display_name }} - {{ item.state }} "
      loop: "{{ services_list.services }}"
      when: item.start_mode != 'disabled'
      
    - name: Filter enabled services with auto_start or delayed start types
      set_fact:
        filtered_services: "{{ services_list.services | selectattr('start_mode', '!=', 'disabled') | selectattr('start_mode', 'in', ['auto', 'delayed']) | selectattr ('state', '==', 'stopped') | list }}"

    - name: Display the filtered services
      debug:
        msg: "{{ item.display_name }}, {{ item.state }} - {{ item.description }}"
      loop: "{{ filtered_services }}"      
