---
- name: List all enabled windows services and highlight stopped automatic service on Windows
  hosts: windows_servers
  gather_facts: no
  tasks:

    - name: List all services on the Windows machine
      ansible.windows.win_service_info:
      register: services_list

    - name: Display the names of enabled services only
      debug:
        msg: "{{ item.display_name }}, {{ item.state }} "
      loop: "{{ services_list.services }}"
      when: item.start_mode != 'disabled'
      
    - name: Display the names of enabled automatic services only but stopped
      debug:
        msg: "{{ item.display_name }}, {{ item.state }} {{ item.description }} "
      loop: "{{ services_list.services }}"
      when: item.start_mode != 'disabled' and item.state == 'stopped' and (item.start_mode == 'auto' or item.start_mode == 'delayed')
