---
- name: Unlock domain user and change password
  hosts: windows_servers
  gather_facts: no
  tasks:
    - name: Unlock the domain user
      ansible.windows.win_user:
        name: "{{ domain_user }}"
        password_never_expires: false
        account_locked: false
        account_disabled: false
      register: user_unlocked

    - name: Generate a new password for the user
      set_fact:
        new_password: "{{ lookup('community.general.random_string', length=12, min_lower=1, min_upper=1, min_numeric=1, min_special=1, override_special='-_=+!#$()[]') }}"

    - name: Change the domain user password
      ansible.windows.win_user:
        name: "{{ domain_user }}"
        password: "{{ new_password }}"
        update_password: always
      when: user_unlocked.changed

    - name: Save the domain_user and new_password as facts
      set_fact:
        saved_domain_user: "{{ domain_user }}"
        saved_new_password: "{{ new_password }}"

- name: Output username and password to a JSON file
  hosts: local
    vars: ansible_port=22
  gather_facts: no
  tasks:
    - name: Output username and password to a JSON file on local machine
      copy:
        content: |
          {
            "username": "{{ hostvars[groups['windows_servers'][0]].saved_domain_user }}",
            "password": "{{ hostvars[groups['windows_servers'][0]].saved_new_password }}"
          }
        dest: "/home/sysowner/output.json"
