- name: update cname
  hosts: windows_servers
  gather_facts: no
  tasks:
    - name: Update DNS record
      community.windows.win_dns_record:
        name: "{{ cname }}.{{ dns_zone }}"
        zone: "{{ dns_zone }}"
        type: A
        value: "{{ target_fqdn }}.{{ dns_zone }}"
        state: present
        computer_name: "{{ dns_server_fqdn }}"
