- name: update cname
  hosts: windows_servers
  gather_facts: no
  tasks:
    - name: Update CNAME DNS record
      community.windows.win_dns_record:
        name: "{{ cname }}"
        zone: "{{ dns_zone }}"
        type: CNAME
        value: "{{ target_fqdn }}"
        state: present
        computer_name: "{{ dns_server_fqdn }}"
