- name: Updatedns.yaml
  hosts: windows_servers
  gather_facts: no
  tasks:
    - name: Update DNS record
      community.windows.win_dns_record:
        name: "{{ record_name }}"
        zone: "{{ dns_zone }}"
        type: A
        value: "{{ record_ip }}"
        state: present
        computer_name: "AIOSERVER.LOCAL.DOMAIN"

    - name: Update PTR record
      community.windows.win_dns_record:
        name: "{{ record_name }}"
        zone: "{{ dns_zone }}"
        type: PTR
        value: "{{ record_ip }}"
