- name: Check for Windows Updates
  hosts: windows_servers
  gather_facts: no

  tasks:
    - name: Search for Windows Updates
      ansible.windows.win_updates:
        category_names: '*'
        server_selection: 'windows_update'
        state: searched
      register: check_win_updates_patch_result
      
    - name: Install Windows Updates
      ansible.windows.win_updates:
        category_names: '*'
        server_selection: 'windows_update'
        state: installed
      register: check_win_updates_patch_result
