- name: Reboot Windows Machine if updates installed
  hosts: windows_servers
  become: no
  gather_facts: no

  tasks:
    - name: Check for pending updates
      ansible.windows.win_updates:
        state: installed

    - name: Reboot if updates installed
      ansible.windows.win_reboot:
        reboot_timeout: 600
