- name: Reboot Windows Machine if updates installed
  hosts: windows_servers
  become: no

  tasks:
    - name: Check for pending updates
      ansible.windows.win_updates_fact:
        state: present

    - name: Reboot if updates installed
      ansible.windows.win_reboot:
        when: ansible_facts.win_updates.pending_reboot
