---

collections:
  # for common collections:
  - 'community.general'
  - 'ansible.posix'
  - 'community.mysql'
  - 'ansible.windows'
  - 'microsoft.ad'
  - 'community.general.proxmox'
  - 'vmware.vmware.vms'
