---
- name: install if updates available.
  become: true
  become_method: sudo
  become_user: root
  hosts: linux
  gather_facts: no

  tasks:
    - name: "[RHEL] Update packages"
      ansible.builtin.dnf:
        update_cache: yes
        name: "*"
        state: latest
