---
- name: install if updates available.
  hosts: linux
  become: no
  gather_facts: no

  tasks:
    - name: "[RHEL] Update packages"
      ansible.builtin.dnf:
        update_cache: yes
        name: "*"
        state: latest

    - name: Reboot a slow machine that might have lots of updates to apply
      ansible.builtin.reboot:
        reboot_timeout: 3600